#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)

library(org.Hs.eg.db)
library(ReactomePA)

# Create reports directory if it doesn't exist.
if (!dir.exists("reports")){
  dir.create("reports")
}

# Load the input generated by dvt_analysis.R
report_input <- readRDS(paste0("reports/", args[1], "_report_input.Rds"))

# Create HTML markdown report.
rmarkdown::render("R/dvt_report.Rmd",
  knit_root_dir = getwd(),
  output_file = paste0("../reports/", args[1], "_report.html")
)

rm(list = ls())
gc()
